#[path = "auth_tab_shows_provider_test_result_inline_to_provider_tab_parts/settings_handles_empty_state_to_auth_tab_shows_chatgpt_logout.rs"]
mod settings_handles_empty_state_to_auth_tab_shows_chatgpt_logout;
#[path = "auth_tab_shows_provider_test_result_inline_to_provider_tab_parts/auth_tab_shows_provider_test_result_inline_to_provider_tab_hides.rs"]
mod auth_tab_shows_provider_test_result_inline_to_provider_tab_hides;
#[path = "auth_tab_shows_provider_test_result_inline_to_provider_tab_parts/provider_tab_shows_openrouter_rows_for_openrouter_provider_to_features.rs"]
mod provider_tab_shows_openrouter_rows_for_openrouter_provider_to_features;
