#[path = "get_operator_profile_summary_to_resolve_task_approval_parts/get_operator_profile_summary_to_resolve_task_approval.rs"]
mod get_operator_profile_summary_to_resolve_task_approval;
#[path = "get_operator_profile_summary_to_resolve_task_approval_parts/request_agent_status_to_defer_operator_profile_question.rs"]
mod request_agent_status_to_defer_operator_profile_question;
