use super::*;

#[path = "collaboration_mouse_clicks_select_rows_and_vote_actions_parts/goal_sidebar_tab_cycling_stays.rs"]
pub(super) mod goal_sidebar_tab_cycling_stays;
#[path = "collaboration_mouse_clicks_select_rows_and_vote_actions_parts/goal_sidebar_row_selection_clamps_per_active_tab_to_goal_workspace.rs"]
mod goal_sidebar_row_selection_clamps_per_active_tab_to_goal_workspace;
#[path = "collaboration_mouse_clicks_select_rows_and_vote_actions_parts/goal_workspace_plan_prompt_toggle_is_clickable_and_keyboard_expandable.rs"]
mod goal_workspace_plan_prompt_toggle_is_clickable_and_keyboard_expandable;
#[path = "collaboration_mouse_clicks_select_rows_and_vote_actions_parts/threads_return_to_goal_banner_keeps_conversation_mouse_targets_aligned.rs"]
mod threads_return_to_goal_banner_keeps_conversation_mouse_targets_aligned;
#[path = "collaboration_mouse_clicks_select_rows_and_vote_actions_parts/goal_workspace_keyboard_navigation_auto_scrolls_timeline_to_chat_unpin.rs"]
mod goal_workspace_keyboard_navigation_auto_scrolls_timeline_to_chat_unpin;
#[path = "collaboration_mouse_clicks_select_rows_and_vote_actions_parts/submit_operator_profile_answer_allows_empty_input_when_question.rs"]
pub(super) mod submit_operator_profile_answer_allows_empty_input_when_question;
#[path = "collaboration_mouse_clicks_select_rows_and_vote_actions_parts/collaboration_mouse_clicks_select_rows_and_vote_actions_to_submit_prompt.rs"]
mod collaboration_mouse_clicks_select_rows_and_vote_actions_to_submit_prompt;

pub(super) use goal_sidebar_tab_cycling_stays as goal_sidebar_tab_cycling_stays_mod;
pub(super) use submit_operator_profile_answer_allows_empty_input_when_question as submit_operator_profile_answer_allows_empty_input_when_question_mod;

