// Widget modules
pub mod approval;
pub mod chat;
pub mod command_palette;
pub mod footer;
pub mod goal_picker;
pub mod header;
pub mod message;
pub mod model_picker;
pub mod provider_picker;
pub mod reasoning;
pub mod settings;
pub mod sidebar;
pub mod splash;
pub mod subagents;
pub mod task_tree;
pub mod task_view;
pub mod thread_picker;
pub mod work_context_view;
