#[path = "message_parts/markdown_renders_bold_to_apply_patch_tool_message_expanded_renders_diff.rs"]
mod markdown_renders_bold_to_apply_patch_tool_message_expanded_renders_diff;
#[path = "message_parts/tool_message_expanded_formats_json_arguments_and_result_as_key_values.rs"]
mod tool_message_expanded_formats_json_arguments_and_result_as_key_values;
#[path = "message_parts/reasoning_renders_before_multiline_content_to_wrap_text_zero_width.rs"]
mod reasoning_renders_before_multiline_content_to_wrap_text_zero_width;
