#[path = "sidebar_parts/sidebar_handles_empty_state_to_spawned_sidebar_tabs_include_spawned.rs"]
mod sidebar_handles_empty_state_to_spawned_sidebar_tabs_include_spawned;
#[path = "sidebar_parts/spawned_sidebar_renders_disabled_rows.rs"]
mod spawned_sidebar_renders_disabled_rows;
