#[path = "events_tasks_parts/is_placeholder_goal_run_detail_to_handle_thread_detail_event.rs"]
mod is_placeholder_goal_run_detail_to_handle_thread_detail_event;

#[path = "events_tasks_parts/handle_thread_created_event_to_handle_file_preview_event.rs"]
mod handle_thread_created_event_to_handle_file_preview_event;
