export const TOOL_NAMES = {
  activateGeneratedTool: "activate_generated_tool",
  agentQueryMemory: "agent_query_memory",
  addTrigger: "add_trigger",
  advanceDebateRound: "advance_debate_round",
  allocateTerminal: "allocate_terminal",
  analyzeImage: "analyze_image",
  appendDebateArgument: "append_debate_argument",
  appendToFile: "append_to_file",
  applyFilePatch: "apply_file_patch",
  applyPatch: "apply_patch",
  askQuestions: "ask_questions",
  bashCommand: "bash_command",
  broadcastContribution: "broadcast_contribution",
  browserBack: "browser_back",
  browserClick: "browser_click",
  browserEvalJs: "browser_eval_js",
  browserForward: "browser_forward",
  browserGetElements: "browser_get_elements",
  browserNavigate: "browser_navigate",
  browserReadDom: "browser_read_dom",
  browserReload: "browser_reload",
  browserScroll: "browser_scroll",
  browserTakeScreenshot: "browser_take_screenshot",
  browserType: "browser_type",
  cancelTask: "cancel_task",
  completeDebateSession: "complete_debate_session",
  controlGoalRun: "control_goal_run",
  createBrowserProfile: "create_browser_profile",
  createFile: "create_file",
  createRoutine: "create_routine",
  createSnippet: "create_snippet",
  createSurface: "create_surface",
  createWorkspace: "create_workspace",
  decodeEmergentProtocol: "decode_emergent_protocol",
  deleteRoutine: "delete_routine",
  discoverGuidelines: "discover_guidelines",
  discoverSkills: "discover_skills",
  dispatchViaBidProtocol: "dispatch_via_bid_protocol",
  equalizeLayout: "equalize_layout",
  enqueueTask: "enqueue_task",
  executeCommand: "execute_command",
  executeManagedCommand: "execute_managed_command",
  fetchAuthenticatedProviders: "fetch_authenticated_providers",
  fetchGatewayHistory: "fetch_gateway_history",
  fetchProviderModels: "fetch_provider_models",
  fetchUrl: "fetch_url",
  findSymbol: "find_symbol",
  generateImage: "generate_image",
  generateSoc2Artifact: "generate_soc2_artifact",
  getBackgroundTaskStatus: "get_background_task_status",
  getCausalTraceReport: "get_causal_trace_report",
  getCollaborationSessions: "get_collaboration_sessions",
  getCostSummary: "get_cost_summary",
  getCounterfactualReport: "get_counterfactual_report",
  getCritiqueSession: "get_critique_session",
  getCurrentDatetime: "get_current_datetime",
  getDebateSession: "get_debate_session",
  getDivergentSession: "get_divergent_session",
  getEmergentProtocolUsageLog: "get_emergent_protocol_usage_log",
  getGitLineStatuses: "get_git_line_statuses",
  getGitStatus: "get_git_status",
  getGoalRun: "get_goal_run",
  getMemoryProvenanceReport: "get_memory_provenance_report",
  getOperationStatus: "get_operation_status",
  getOperatorModel: "get_operator_model",
  getProvenanceReport: "get_provenance_report",
  getRoutine: "get_routine",
  getSystemInfo: "get_system_info",
  getTerminalContent: "get_terminal_content",
  getThread: "get_thread",
  getTodos: "get_todos",
  handoffThreadAgent: "handoff_thread_agent",
  imageQuery: "image_query",
  importExternalRuntime: "import_external_runtime",
  ingestWebhookEvent: "ingest_webhook_event",
  inspectSkillVariant: "inspect_skill_variant",
  justifySkillSkip: "justify_skill_skip",
  listAgents: "list_agents",
  listBrowserProfiles: "list_browser_profiles",
  listCollaborationSessions: "list_collaboration_sessions",
  listEmergentProtocolProposals: "list_emergent_protocol_proposals",
  listFiles: "list_files",
  listGeneratedTools: "list_generated_tools",
  listGoalRuns: "list_goal_runs",
  listGuidelines: "list_guidelines",
  listModels: "list_models",
  listParticipants: "list_participants",
  listProcesses: "list_processes",
  listProviders: "list_providers",
  listRoutineHistory: "list_routine_history",
  listRoutines: "list_routines",
  listSessions: "list_sessions",
  listSkillVariants: "list_skill_variants",
  listSkills: "list_skills",
  listSnapshots: "list_snapshots",
  listSnippets: "list_snippets",
  listSubagents: "list_subagents",
  listTasks: "list_tasks",
  listTerminals: "list_terminals",
  listThreads: "list_threads",
  listTools: "list_tools",
  listTodos: "list_todos",
  listTriggerFireHistory: "list_trigger_fire_history",
  listTriggers: "list_triggers",
  listWorkspaces: "list_workspaces",
  lookupEmergentProtocol: "lookup_emergent_protocol",
  messageAgent: "message_agent",
  notifyUser: "notify_user",
  onecontextSearch: "onecontext_search",
  openCanvasBrowser: "open_canvas_browser",
  pauseRoutine: "pause_routine",
  pluginApiCall: "plugin_api_call",
  previewRoutine: "preview_routine",
  previewShadowRun: "preview_shadow_run",
  promoteGeneratedTool: "promote_generated_tool",
  pythonExecute: "python_execute",
  queryAudits: "query_audits",
  readActiveTerminalContent: "read_active_terminal_content",
  readFile: "read_file",
  readGuideline: "read_guideline",
  readMemory: "read_memory",
  readOffloadedPayload: "read_offloaded_payload",
  readPeerMemory: "read_peer_memory",
  readSkill: "read_skill",
  readSoul: "read_soul",
  readUser: "read_user",
  reloadEmergentProtocolRegistry: "reload_emergent_protocol_registry",
  replaceInFile: "replace_in_file",
  renamePane: "rename_pane",
  rerunRoutine: "rerun_routine",
  respondEmergentProtocolProposal: "respond_emergent_protocol_proposal",
  resetOperatorModel: "reset_operator_model",
  restoreGeneratedTool: "restore_generated_tool",
  restoreSnapshot: "restore_snapshot",
  resumeRoutine: "resume_routine",
  routeToSpecialist: "route_to_specialist",
  runTerminalCommand: "run_terminal_command",
  runDebate: "run_debate",
  runDivergent: "run_divergent",
  runGeneratedTool: "run_generated_tool",
  runRoutineNow: "run_routine_now",
  runWorkflowPack: "run_workflow_pack",
  runSnippet: "run_snippet",
  searchFiles: "search_files",
  searchHistory: "search_history",
  searchMemory: "search_memory",
  searchQuery: "search_query",
  searchSoul: "search_soul",
  searchUser: "search_user",
  scrubSensitive: "scrub_sensitive",
  semanticQuery: "semantic_query",
  sendDiscordMessage: "send_discord_message",
  sendSlackMessage: "send_slack_message",
  sendTelegramMessage: "send_telegram_message",
  sendWhatsAppMessage: "send_whatsapp_message",
  sessionSearch: "session_search",
  setActiveSurface: "set_active_surface",
  setActiveWorkspace: "set_active_workspace",
  setLayoutPreset: "set_layout_preset",
  setupWebBrowsing: "setup_web_browsing",
  showDreams: "show_dreams",
  showHarnessState: "show_harness_state",
  showImportReport: "show_import_report",
  speechToText: "speech_to_text",
  splitPane: "split_pane",
  spawnSubagent: "spawn_subagent",
  startGoalRun: "start_goal_run",
  submitGoalStepVerdict: "submit_goal_step_verdict",
  summary: "summary",
  switchModel: "switch_model",
  synthesizeTool: "synthesize_tool",
  textToSpeech: "text_to_speech",
  toolSearch: "tool_search",
  typeInTerminal: "type_in_terminal",
  updateBrowserProfileHealth: "update_browser_profile_health",
  updateMemory: "update_memory",
  updateRoutine: "update_routine",
  updateTodo: "update_todo",
  verifyIntegrity: "verify_integrity",
  voteOnDisagreement: "vote_on_disagreement",
  webRun: "web.run",
  webSearch: "web_search",
  workspaceCreateTask: "workspace_create_task",
  workspaceDeleteTask: "workspace_delete_task",
  workspaceGetSettings: "workspace_get_settings",
  workspaceGetTask: "workspace_get_task",
  workspaceListNotices: "workspace_list_notices",
  workspaceListTasks: "workspace_list_tasks",
  workspaceMoveTask: "workspace_move_task",
  workspacePauseTask: "workspace_pause_task",
  workspaceRunTask: "workspace_run_task",
  workspaceSetOperator: "workspace_set_operator",
  workspaceStopTask: "workspace_stop_task",
  workspaceSubmitCompletion: "workspace_submit_completion",
  workspaceSubmitReview: "workspace_submit_review",
  workspaceUpdateTask: "workspace_update_task",
  writeFile: "write_file",
} as const;

export type ToolName = (typeof TOOL_NAMES)[keyof typeof TOOL_NAMES];

export const TOOL_NAME_PREFIXES = {
  browser: "browser_",
  plugin: "plugin_",
} as const;

export const TOOL_NAME_FRAGMENTS = {
  generatedTool: "generated_tool",
  plugin: "_plugin_",
  terminal: "terminal",
  webBrowsing: "web_brows",
} as const;

export const TOOL_NAME_GROUPS = {
  web: [
    TOOL_NAMES.webSearch,
    TOOL_NAMES.fetchUrl,
    TOOL_NAMES.setupWebBrowsing,
    TOOL_NAMES.openCanvasBrowser,
    TOOL_NAMES.listBrowserProfiles,
    TOOL_NAMES.createBrowserProfile,
    TOOL_NAMES.updateBrowserProfileHealth,
    TOOL_NAMES.searchQuery,
    TOOL_NAMES.imageQuery,
    TOOL_NAMES.webRun,
  ],
  guideline: [
    TOOL_NAMES.listGuidelines,
    TOOL_NAMES.discoverGuidelines,
    TOOL_NAMES.readGuideline,
  ],
  skill: [
    TOOL_NAMES.listSkills,
    TOOL_NAMES.discoverSkills,
    TOOL_NAMES.readSkill,
    TOOL_NAMES.justifySkillSkip,
    TOOL_NAMES.synthesizeTool,
    TOOL_NAMES.activateGeneratedTool,
    TOOL_NAMES.promoteGeneratedTool,
    TOOL_NAMES.restoreGeneratedTool,
    TOOL_NAMES.listGeneratedTools,
    TOOL_NAMES.runGeneratedTool,
    TOOL_NAMES.listSkillVariants,
    TOOL_NAMES.inspectSkillVariant,
  ],
  terminal: [
    TOOL_NAMES.executeCommand,
    TOOL_NAMES.bashCommand,
    TOOL_NAMES.runTerminalCommand,
    TOOL_NAMES.executeManagedCommand,
    TOOL_NAMES.listTerminals,
    TOOL_NAMES.readActiveTerminalContent,
    TOOL_NAMES.allocateTerminal,
    TOOL_NAMES.typeInTerminal,
    TOOL_NAMES.getOperationStatus,
    TOOL_NAMES.getBackgroundTaskStatus,
    TOOL_NAMES.getTerminalContent,
  ],
  file: [
    TOOL_NAMES.listFiles,
    TOOL_NAMES.readFile,
    TOOL_NAMES.getGitLineStatuses,
    TOOL_NAMES.writeFile,
    TOOL_NAMES.createFile,
    TOOL_NAMES.appendToFile,
    TOOL_NAMES.replaceInFile,
    TOOL_NAMES.applyFilePatch,
    TOOL_NAMES.applyPatch,
    TOOL_NAMES.readOffloadedPayload,
  ],
  search: [
    TOOL_NAMES.searchFiles,
    TOOL_NAMES.searchHistory,
    TOOL_NAMES.findSymbol,
    TOOL_NAMES.sessionSearch,
    TOOL_NAMES.onecontextSearch,
    TOOL_NAMES.semanticQuery,
    TOOL_NAMES.summary,
    TOOL_NAMES.toolSearch,
  ],
  memory: [
    TOOL_NAMES.agentQueryMemory,
    TOOL_NAMES.updateMemory,
    TOOL_NAMES.readMemory,
    TOOL_NAMES.readUser,
    TOOL_NAMES.readSoul,
    TOOL_NAMES.searchMemory,
    TOOL_NAMES.searchUser,
    TOOL_NAMES.searchSoul,
    TOOL_NAMES.readPeerMemory,
  ],
  workspace: [
    TOOL_NAMES.listWorkspaces,
    TOOL_NAMES.createWorkspace,
    TOOL_NAMES.setActiveWorkspace,
    TOOL_NAMES.createSurface,
    TOOL_NAMES.setActiveSurface,
    TOOL_NAMES.splitPane,
    TOOL_NAMES.renamePane,
    TOOL_NAMES.setLayoutPreset,
    TOOL_NAMES.equalizeLayout,
    TOOL_NAMES.listSnippets,
    TOOL_NAMES.createSnippet,
    TOOL_NAMES.runSnippet,
    TOOL_NAMES.workspaceGetSettings,
    TOOL_NAMES.workspaceListTasks,
    TOOL_NAMES.workspaceGetTask,
    TOOL_NAMES.workspaceListNotices,
    TOOL_NAMES.workspaceSetOperator,
    TOOL_NAMES.workspaceCreateTask,
    TOOL_NAMES.workspaceUpdateTask,
    TOOL_NAMES.workspaceMoveTask,
    TOOL_NAMES.workspaceRunTask,
    TOOL_NAMES.workspacePauseTask,
    TOOL_NAMES.workspaceStopTask,
    TOOL_NAMES.workspaceDeleteTask,
    TOOL_NAMES.workspaceSubmitReview,
    TOOL_NAMES.workspaceSubmitCompletion,
  ],
  communication: [
    TOOL_NAMES.notifyUser,
    TOOL_NAMES.askQuestions,
    TOOL_NAMES.sendSlackMessage,
    TOOL_NAMES.sendDiscordMessage,
    TOOL_NAMES.sendTelegramMessage,
    TOOL_NAMES.sendWhatsAppMessage,
  ],
  audio: [TOOL_NAMES.speechToText, TOOL_NAMES.textToSpeech, TOOL_NAMES.analyzeImage],
  system: [
    TOOL_NAMES.getSystemInfo,
    TOOL_NAMES.listProcesses,
    TOOL_NAMES.getCurrentDatetime,
    TOOL_NAMES.getCostSummary,
    TOOL_NAMES.showDreams,
    TOOL_NAMES.showHarnessState,
    TOOL_NAMES.importExternalRuntime,
    TOOL_NAMES.showImportReport,
    TOOL_NAMES.previewShadowRun,
    TOOL_NAMES.listTools,
    TOOL_NAMES.fetchGatewayHistory,
    TOOL_NAMES.listSnapshots,
    TOOL_NAMES.restoreSnapshot,
    TOOL_NAMES.scrubSensitive,
    TOOL_NAMES.verifyIntegrity,
    TOOL_NAMES.getOperatorModel,
    TOOL_NAMES.resetOperatorModel,
    TOOL_NAMES.getCausalTraceReport,
    TOOL_NAMES.getCounterfactualReport,
    TOOL_NAMES.getMemoryProvenanceReport,
    TOOL_NAMES.getProvenanceReport,
    TOOL_NAMES.queryAudits,
    TOOL_NAMES.generateSoc2Artifact,
    TOOL_NAMES.getGitStatus,
  ],
  model: [
    TOOL_NAMES.fetchAuthenticatedProviders,
    TOOL_NAMES.listProviders,
    TOOL_NAMES.fetchProviderModels,
    TOOL_NAMES.listModels,
    TOOL_NAMES.switchModel,
  ],
  agent: [
    TOOL_NAMES.listAgents,
    TOOL_NAMES.listParticipants,
    TOOL_NAMES.spawnSubagent,
    TOOL_NAMES.listSubagents,
    TOOL_NAMES.messageAgent,
    TOOL_NAMES.handoffThreadAgent,
    TOOL_NAMES.routeToSpecialist,
  ],
  task: [
    TOOL_NAMES.updateTodo,
    TOOL_NAMES.getTodos,
    TOOL_NAMES.listTodos,
    TOOL_NAMES.enqueueTask,
    TOOL_NAMES.listTasks,
    TOOL_NAMES.cancelTask,
  ],
  goal: [
    TOOL_NAMES.startGoalRun,
    TOOL_NAMES.listGoalRuns,
    TOOL_NAMES.getGoalRun,
    TOOL_NAMES.controlGoalRun,
    TOOL_NAMES.submitGoalStepVerdict,
  ],
  routine: [
    TOOL_NAMES.createRoutine,
    TOOL_NAMES.listRoutines,
    TOOL_NAMES.getRoutine,
    TOOL_NAMES.previewRoutine,
    TOOL_NAMES.updateRoutine,
    TOOL_NAMES.runRoutineNow,
    TOOL_NAMES.listRoutineHistory,
    TOOL_NAMES.rerunRoutine,
    TOOL_NAMES.pauseRoutine,
    TOOL_NAMES.resumeRoutine,
    TOOL_NAMES.deleteRoutine,
  ],
  trigger: [
    TOOL_NAMES.listTriggers,
    TOOL_NAMES.ingestWebhookEvent,
    TOOL_NAMES.addTrigger,
    TOOL_NAMES.listTriggerFireHistory,
  ],
  workflow: [TOOL_NAMES.runWorkflowPack],
  debate: [
    TOOL_NAMES.runDivergent,
    TOOL_NAMES.getDivergentSession,
    TOOL_NAMES.runDebate,
    TOOL_NAMES.getDebateSession,
    TOOL_NAMES.advanceDebateRound,
    TOOL_NAMES.completeDebateSession,
    TOOL_NAMES.appendDebateArgument,
    TOOL_NAMES.getCritiqueSession,
  ],
  collaboration: [
    TOOL_NAMES.broadcastContribution,
    TOOL_NAMES.readPeerMemory,
    TOOL_NAMES.voteOnDisagreement,
    TOOL_NAMES.dispatchViaBidProtocol,
    TOOL_NAMES.listCollaborationSessions,
    TOOL_NAMES.getCollaborationSessions,
  ],
  plugin: [TOOL_NAMES.pluginApiCall],
  thread: [
    TOOL_NAMES.listThreads,
    TOOL_NAMES.getThread,
    TOOL_NAMES.lookupEmergentProtocol,
    TOOL_NAMES.listEmergentProtocolProposals,
    TOOL_NAMES.respondEmergentProtocolProposal,
    TOOL_NAMES.reloadEmergentProtocolRegistry,
    TOOL_NAMES.decodeEmergentProtocol,
  ],
} as const;
