#!/usr/bin/env bash
# Re-copy the deepmind scripts for every sub-plugin of zorai-plugin-science
# from the vendored bundle, and copy the shared scienceskillscommon package
# once at the package root.
#
# Usage: ./sync-from-bundle.sh
#
# This is a build-time helper. After refreshing skills/scientific-skills-gdm/
# from upstream, run this once at the package root to update all sub-plugins.
#
# Background: the deepmind scripts embed a PEP 723 sources entry
#   [tool.uv.sources]
#   scienceskillscommon = { path = "../../scienceskillscommon" }
# which resolves relative to the script file. In the upstream bundle, a
# script at <bundle>/<skill>/scripts/foo.py sees `../../` as <bundle>/, so
# `../../scienceskillscommon` lands at the bundle root. The same script
# copied to plugins/zorai-plugin-science/<sub>/scripts/foo.py then needs
# scienceskillscommon at the package root (plugins/zorai-plugin-science/),
# not at the per-sub-plugin level. Hence: one shared copy at the root.

set -euo pipefail

PLUGIN_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$PLUGIN_DIR/../.." && pwd)"
BUNDLE="$REPO_ROOT/skills/scientific-skills-gdm"

if [ ! -d "$BUNDLE" ]; then
  echo "Bundle not found: $BUNDLE" >&2
  echo "  (is skills/scientific-skills-gdm/ vendored at the repo root?)" >&2
  exit 1
fi

# Map: sub-plugin dir name -> deepmind skill dir name.
# To add a new sub-plugin: add the mapping here, then add a new entry under
# plugins/zorai-plugin-science/<name>/ with a matching plugin.json and
# skills/<name>.md. The "full" sub-plugins have hand-written plugin.json
# files; the "long-tail" sub-plugins get a stub plugin.json generated by
# tools/generate_longtail_stubs.py.
declare -A SKILL_DIRS=(
  # Full sub-plugins (hand-written plugin.json with named commands).
  [alphagenome]="alphagenome_single_variant_analysis"
  [alphafold-database]="alphafold_database_fetch_and_analyze"
  [uniprot]="uniprot_database"
  [clinvar]="clinvar_database"
  [chembl]="chembl_database"
  [openalex]="literature_search_openalex"
  [ensembl]="ensembl_database"
  [reactome]="reactome_database"
  [gnomad]="gnomad_database"
  # Long-tail sub-plugins (stub plugin.json with a single `run` command).
  [clinical-trials-database]="clinical_trials_database"
  [dbsnp-database]="dbsnp_database"
  [embl-ebi-ols]="embl_ebi_ols"
  [encode-ccres-database]="encode_ccres_database"
  [foldseek-structural-search]="foldseek_structural_search"
  [gtex-database]="gtex_database"
  [human-protein-atlas-database]="human_protein_atlas_database"
  [interpro-database]="interpro_database"
  [jaspar-database]="jaspar_database"
  [literature-search-arxiv]="literature_search_arxiv"
  [literature-search-biorxiv]="literature_search_biorxiv"
  [literature-search-europepmc]="literature_search_europepmc"
  [ncbi-sequence-fetch]="ncbi_sequence_fetch"
  [openfda-database]="openfda_database"
  [opentargets-database]="opentargets_database"
  [pdb-database]="pdb_database"
  [protein-sequence-msa]="protein_sequence_msa"
  [protein-sequence-similarity-search]="protein_sequence_similarity_search"
  [pubchem-database]="pubchem_database"
  [pubmed-database]="pubmed_database"
  [pymol]="pymol"
  [quickgo-database]="quickgo_database"
  [string-database]="string_database"
  [ucsc-conservation-and-tfbs]="ucsc_conservation_and_tfbs"
  [unibind-database]="unibind_database"
)

for sub in "${!SKILL_DIRS[@]}"; do
  skill_dir="${SKILL_DIRS[$sub]}"
  src="$BUNDLE/$skill_dir/scripts"
  dst="$PLUGIN_DIR/$sub/scripts"
  if [ ! -d "$src" ]; then
    echo "SKIP $sub: source $src not found" >&2
    continue
  fi
  mkdir -p "$dst"
  rm -rf "$dst"/*
  cp -r "$src/." "$dst/"
  echo "OK $sub: scripts -> $dst ($(ls "$dst" | wc -l) files)"
done

# scienceskillscommon lives at the package root, shared across sub-plugins.
SCICOMMON_SRC="$BUNDLE/scienceskillscommon"
SCICOMMON_DST="$PLUGIN_DIR/scienceskillscommon"
if [ -d "$SCICOMMON_SRC" ]; then
  rm -rf "$SCICOMMON_DST"
  cp -r "$SCICOMMON_SRC" "$SCICOMMON_DST"
  echo "OK scienceskillscommon -> $SCICOMMON_DST"
fi

echo
echo "All sub-plugins synced from $BUNDLE"
echo "Pin: $(cat $BUNDLE/UPSTREAM_PIN.txt 2>/dev/null || echo '<no pin file>')"
