use amux_shared::providers::*;
use super::ProviderDef;

pub const CHAT_ONLY_TRANSPORTS: &[&str] = &["chat_completions"];
pub const RESPONSES_AND_CHAT_TRANSPORTS: &[&str] = &["responses", "chat_completions"];
pub const NATIVE_AND_CHAT_TRANSPORTS: &[&str] = &["native_assistant", "chat_completions"];
pub const API_KEY_ONLY_AUTH_SOURCES: &[&str] = &["api_key"];
pub const OPENAI_AUTH_SOURCES: &[&str] = &["chatgpt_subscription", "api_key"];
pub const GITHUB_COPILOT_AUTH_SOURCES: &[&str] = &["github_copilot", "api_key"];

pub const PROVIDERS: &[ProviderDef] = &[
    ProviderDef {
        id: PROVIDER_ID_OPENAI,
        name: "OpenAI / ChatGPT",
        default_base_url: "https://api.openai.com/v1",
        default_model: "gpt-5.4",
        supported_transports: RESPONSES_AND_CHAT_TRANSPORTS,
        default_transport: "responses",
        supported_auth_sources: OPENAI_AUTH_SOURCES,
        default_auth_source: "api_key",
        native_base_url: None,
    },
    ProviderDef {
        id: PROVIDER_ID_GITHUB_COPILOT,
        name: "GitHub Copilot",
        default_base_url: "https://api.githubcopilot.com",
        default_model: "gpt-4.1",
        supported_transports: RESPONSES_AND_CHAT_TRANSPORTS,
        default_transport: "responses",
        supported_auth_sources: GITHUB_COPILOT_AUTH_SOURCES,
        default_auth_source: "github_copilot",
        native_base_url: None,
    },
    ProviderDef {
        id: PROVIDER_ID_GROQ,
        name: "Groq",
        default_base_url: "https://api.groq.com/openai/v1",
        default_model: "llama-3.3-70b-versatile",
        supported_transports: RESPONSES_AND_CHAT_TRANSPORTS,
        default_transport: "responses",
        supported_auth_sources: API_KEY_ONLY_AUTH_SOURCES,
        default_auth_source: "api_key",
        native_base_url: None,
    },
    ProviderDef {
        id: PROVIDER_ID_OLLAMA,
        name: "Ollama",
        default_base_url: "http://localhost:11434/v1",
        default_model: "llama3.1",
        supported_transports: CHAT_ONLY_TRANSPORTS,
        default_transport: "chat_completions",
        supported_auth_sources: API_KEY_ONLY_AUTH_SOURCES,
        default_auth_source: "api_key",
        native_base_url: None,
    },
    ProviderDef {
        id: PROVIDER_ID_TOGETHER,
        name: "Together",
        default_base_url: "https://api.together.xyz/v1",
        default_model: "meta-llama/Llama-3.3-70B-Instruct-Turbo",
        supported_transports: CHAT_ONLY_TRANSPORTS,
        default_transport: "chat_completions",
        supported_auth_sources: API_KEY_ONLY_AUTH_SOURCES,
        default_auth_source: "api_key",
        native_base_url: None,
    },
    ProviderDef {
        id: PROVIDER_ID_OPENROUTER,
        name: "OpenRouter",
        default_base_url: "https://openrouter.ai/api/v1",
        default_model: "arcee-ai/trinity-large-thinking",
        supported_transports: CHAT_ONLY_TRANSPORTS,
        default_transport: "chat_completions",
        supported_auth_sources: API_KEY_ONLY_AUTH_SOURCES,
        default_auth_source: "api_key",
        native_base_url: None,
    },
    ProviderDef {
        id: PROVIDER_ID_CEREBRAS,
        name: "Cerebras",
        default_base_url: "https://api.cerebras.ai/v1",
        default_model: "llama-3.3-70b",
        supported_transports: CHAT_ONLY_TRANSPORTS,
        default_transport: "chat_completions",
        supported_auth_sources: API_KEY_ONLY_AUTH_SOURCES,
        default_auth_source: "api_key",
        native_base_url: None,
    },
    ProviderDef {
        id: PROVIDER_ID_QWEN,
        name: "Qwen",
        default_base_url: "https://dashscope-intl.aliyuncs.com/compatible-mode/v1",
        default_model: "qwen-max",
        supported_transports: NATIVE_AND_CHAT_TRANSPORTS,
        default_transport: "native_assistant",
        supported_auth_sources: API_KEY_ONLY_AUTH_SOURCES,
        default_auth_source: "api_key",
        native_base_url: Some("https://dashscope-intl.aliyuncs.com/api/v1"),
    },
    ProviderDef {
        id: PROVIDER_ID_KIMI,
        name: "Kimi (Moonshot)",
        default_base_url: "https://api.moonshot.ai/v1",
        default_model: "moonshot-v1-32k",
        supported_transports: CHAT_ONLY_TRANSPORTS,
        default_transport: "chat_completions",
        supported_auth_sources: API_KEY_ONLY_AUTH_SOURCES,
        default_auth_source: "api_key",
        native_base_url: None,
    },
    ProviderDef {
        id: PROVIDER_ID_Z_AI,
        name: "Z.AI (GLM)",
        default_base_url: "https://api.z.ai/api/paas/v4",
        default_model: "glm-4-plus",
        supported_transports: CHAT_ONLY_TRANSPORTS,
        default_transport: "chat_completions",
        supported_auth_sources: API_KEY_ONLY_AUTH_SOURCES,
        default_auth_source: "api_key",
        native_base_url: None,
    },
    ProviderDef {
        id: PROVIDER_ID_Z_AI_CODING_PLAN,
        name: "Z.AI Coding Plan",
        default_base_url: "https://api.z.ai/api/coding/paas/v4",
        default_model: "glm-5",
        supported_transports: CHAT_ONLY_TRANSPORTS,
        default_transport: "chat_completions",
        supported_auth_sources: API_KEY_ONLY_AUTH_SOURCES,
        default_auth_source: "api_key",
        native_base_url: None,
    },
    ProviderDef {
        id: PROVIDER_ID_KIMI_CODING_PLAN,
        name: "Kimi Coding Plan",
        default_base_url: "https://api.kimi.com/coding/v1",
        default_model: "kimi-for-coding",
        supported_transports: CHAT_ONLY_TRANSPORTS,
        default_transport: "chat_completions",
        supported_auth_sources: API_KEY_ONLY_AUTH_SOURCES,
        default_auth_source: "api_key",
        native_base_url: None,
    },
    ProviderDef {
        id: PROVIDER_ID_MINIMAX,
        name: "MiniMax",
        default_base_url: "https://api.minimax.io/anthropic",
        default_model: "MiniMax-M2.7",
        supported_transports: CHAT_ONLY_TRANSPORTS,
        default_transport: "chat_completions",
        supported_auth_sources: API_KEY_ONLY_AUTH_SOURCES,
        default_auth_source: "api_key",
        native_base_url: None,
    },
    ProviderDef {
        id: PROVIDER_ID_MINIMAX_CODING_PLAN,
        name: "MiniMax Coding Plan",
        default_base_url: "https://api.minimax.io/anthropic",
        default_model: "MiniMax-M2.7",
        supported_transports: CHAT_ONLY_TRANSPORTS,
        default_transport: "chat_completions",
        supported_auth_sources: API_KEY_ONLY_AUTH_SOURCES,
        default_auth_source: "api_key",
        native_base_url: None,
    },
    ProviderDef {
        id: PROVIDER_ID_ALIBABA_CODING_PLAN,
        name: "Alibaba Coding Plan",
        default_base_url: "https://coding-intl.dashscope.aliyuncs.com/v1",
        default_model: "qwen3.5-plus",
        supported_transports: CHAT_ONLY_TRANSPORTS,
        default_transport: "chat_completions",
        supported_auth_sources: API_KEY_ONLY_AUTH_SOURCES,
        default_auth_source: "api_key",
        native_base_url: None,
    },
    ProviderDef {
        id: PROVIDER_ID_QWEN_DEEPINFRA,
        name: "Qwen (DeepInfra)",
        default_base_url: "https://api.deepinfra.com/v1/openai",
        default_model: "Qwen/Qwen2.5-72B-Instruct",
        supported_transports: CHAT_ONLY_TRANSPORTS,
        default_transport: "chat_completions",
        supported_auth_sources: API_KEY_ONLY_AUTH_SOURCES,
        default_auth_source: "api_key",
        native_base_url: None,
    },
    ProviderDef {
        id: PROVIDER_ID_HUGGINGFACE,
        name: "Hugging Face",
        default_base_url: "https://api-inference.huggingface.co/v1",
        default_model: "meta-llama/Llama-3.3-70B-Instruct",
        supported_transports: CHAT_ONLY_TRANSPORTS,
        default_transport: "chat_completions",
        supported_auth_sources: API_KEY_ONLY_AUTH_SOURCES,
        default_auth_source: "api_key",
        native_base_url: None,
    },
    ProviderDef {
        id: PROVIDER_ID_CHUTES,
        name: "Chutes",
        default_base_url: "https://llm.chutes.ai/v1",
        default_model: "deepseek-ai/DeepSeek-V3",
        supported_transports: CHAT_ONLY_TRANSPORTS,
        default_transport: "chat_completions",
        supported_auth_sources: API_KEY_ONLY_AUTH_SOURCES,
        default_auth_source: "api_key",
        native_base_url: None,
    },
    ProviderDef {
        id: PROVIDER_ID_FEATHERLESS,
        name: "Featherless",
        default_base_url: "https://api.featherless.ai/v1",
        default_model: "meta-llama/Llama-3.3-70B-Instruct",
        supported_transports: CHAT_ONLY_TRANSPORTS,
        default_transport: "chat_completions",
        supported_auth_sources: API_KEY_ONLY_AUTH_SOURCES,
        default_auth_source: "api_key",
        native_base_url: None,
    },
    ProviderDef {
        id: PROVIDER_ID_OPENCODE_ZEN,
        name: "OpenCode Zen",
        default_base_url: "https://opencode.ai/zen/v1",
        default_model: "claude-sonnet-4-5",
        supported_transports: CHAT_ONLY_TRANSPORTS,
        default_transport: "chat_completions",
        supported_auth_sources: API_KEY_ONLY_AUTH_SOURCES,
        default_auth_source: "api_key",
        native_base_url: None,
    },
    ProviderDef {
        id: PROVIDER_ID_CUSTOM,
        name: "Custom",
        default_base_url: "",
        default_model: "",
        supported_transports: RESPONSES_AND_CHAT_TRANSPORTS,
        default_transport: "responses",
        supported_auth_sources: API_KEY_ONLY_AUTH_SOURCES,
        default_auth_source: "api_key",
        native_base_url: None,
    },
];
